---
build_from:
  armv7:  ghcr.io/hassio-addons/debian-base/armv7:7.6.2
  aarch64: ghcr.io/hassio-addons/debian-base/aarch64:7.6.2
  amd64:  ghcr.io/hassio-addons/debian-base/amd64:7.6.2


# Build args passed into your Dockerfile (same for all arches)
args:
  FB_VERSION: "4.0.13"      # Fluent Bit version (has x86_64/aarch64/armv7 tarballs)
  TELEGRAF_VERSION: "1.36.3" # Telegraf version (has linux_amd64/arm64/armhf)