---
build_from:
  aarch64: ghcr.io/hassio-addons/debian-base:7.6.2
  amd64: ghcr.io/hassio-addons/debian-base:7.6.2
  armhf: ghcr.io/hassio-addons/debian-base:7.6.2
  armv7: ghcr.io/hassio-addons/debian-base:7.6.2
  i386: ghcr.io/hassio-addons/debian-base:7.6.2

# Build args passed into your Dockerfile (same for all arches)
args:
  FB_VERSION: "4.0.13"      # Fluent Bit version (has x86_64/aarch64/armv7 tarballs)
  TELEGRAF_VERSION: "1.36.3" # Telegraf version (has linux_amd64/arm64/armhf)